version: '2.3'
services:
  tuto_1_python_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    runtime: nvidia
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 10m
