version: '2.3'
services:
  cam_viewer_service:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: stereolabs/iot:0.47.3-runtime-jetson-jp4.4
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
