version: '2.3'
services:
  cam_viewer_service:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: 192.168.1.92:5000/iot:0.57.1-runtime-ubuntu20-cu11.5
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
