version: '2.3'
services: 
  multiplatform_sample:
    build :
        context : ./app
        dockerfile: Dockerfile   
        args:
          BUILD_IMAGE: stereolabs/iot:0.60.0-devel-jetson-l4t32.4
          RUNTIME_IMAGE: stereolabs/iot:0.60.0-runtime-jetson-l4t32.4
    runtime: nvidia
    environment:
     - MESA_GL_VERSION_OVERRIDE=3.3
    privileged: true
    network_mode: "host"